# Generated by Django 4.0.3 on 2022-03-11 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_rename_receitatable_receita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='ingredients',
            new_name='ingredientes',
        ),
    ]
